#spring:
#  application:
#    name: ms-product
#  h2:
#    console:
#      enabled: true
#  zipkin:
#    base-url: http://localhost:9411

server:
  port: 9002

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8762/eureka
#  instance:
#    lease-renewal-interval-in-seconds: 10
#    lease-expiration-duration-in-seconds: 30
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
